{{- if and .Values.metrics.prometheusRule.enabled .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ template "slackgpt.fullname" . }}
  {{- if .Values.metrics.prometheusRule.namespace }}
  namespace: {{ .Values.metrics.prometheusRule.namespace }}
  {{- end }}
  labels: {{- toYaml .Values.metrics.prometheusRule.additionalLabels | nindent 4 }}
spec:
  groups:
    - name: {{ template "slackgpt.fullname" . }}
      {{- if .Values.metrics.prometheusRule.interval }}
      interval: {{ .Values.metrics.prometheusRule.interval }}
      {{- end }}
      rules: {{- tpl (toYaml .Values.metrics.prometheusRule.rules) . | nindent 8 }}
{{- end }}
