{{- if .Values.config }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "slackgpt.fullname" . }}
stringData:
{{- range $path, $config := .Values.config }}
  {{ $path }}: |
{{- if eq (typeOf $config) "string" }}
{{- $config | nindent 4 }}
{{- else }}
{{- toYaml $config | nindent 4 }}
{{- end }}
{{- end -}}
{{- end -}}
