{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "scripts.fullname" . }}
rules:
- resources:
  - '*'
  apiGroups:
  - '*'
  verbs:
  - '*'
{{- end }}
