apiVersion: v1
appVersion: "5.6.4.20"
description: A Helm chart for onlyoffice
name: onlyoffice
version: 1.0.0
icon: https://avatars0.githubusercontent.com/u/22418908?s=200&v=4
sources:
- https://hub.docker.com/r/onlyoffice/documentserver
maintainers:
- name: Kfirfer
  email: kfirfer@gmail.com
home: https://www.onlyoffice.com/
